# Generated by Django 3.2.7 on 2021-09-23 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_product_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='average_order_speed',
            field=models.IntegerField(blank=True, null=True, verbose_name='Средняя скорость заказа'),
        ),
        migrations.AddField(
            model_name='product',
            name='average_unit_profit',
            field=models.IntegerField(blank=True, null=True, verbose_name='Средняя прибыль единицы товара'),
        ),
        migrations.AddField(
            model_name='product',
            name='deliveries',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество поставляется'),
        ),
        migrations.AddField(
            model_name='product',
            name='history',
            field=models.IntegerField(blank=True, null=True, verbose_name='История продаж'),
        ),
        migrations.AddField(
            model_name='product',
            name='need_to_order',
            field=models.IntegerField(blank=True, null=True, verbose_name='Необбходимо заказать'),
        ),
        migrations.AddField(
            model_name='product',
            name='potential_profit',
            field=models.IntegerField(blank=True, null=True, verbose_name='Потенциальная прибыль'),
        ),
        migrations.AddField(
            model_name='product',
            name='reorder_profit',
            field=models.IntegerField(blank=True, null=True, verbose_name='Прибыль перезаказа'),
        ),
        migrations.AddField(
            model_name='product',
            name='reorder_summ',
            field=models.IntegerField(blank=True, null=True, verbose_name='Сумма перезаказа'),
        ),
        migrations.AddField(
            model_name='product',
            name='reordering_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата перезаказа'),
        ),
        migrations.AddField(
            model_name='product',
            name='return_product',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество возвращаемых товаров'),
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(default='wait', max_length=100, verbose_name='Статус закааза'),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_balance',
            field=models.IntegerField(null=True, verbose_name='Остатки на складе'),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_for_days',
            field=models.IntegerField(blank=True, null=True, verbose_name='Запасов на дней'),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Себестоимость остатков'),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_profit',
            field=models.IntegerField(blank=True, null=True, verbose_name='Потенциальная выручка с остатков'),
        ),
        migrations.AddField(
            model_name='product',
            name='way_to_warehous',
            field=models.IntegerField(null=True, verbose_name='В пути на склад'),
        ),
        migrations.DeleteModel(
            name='WarehouseAccounting',
        ),
    ]
