# Generated by Django 3.2.7 on 2021-09-29 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_auto_20210923_0817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='reorder_days_of_supply',
            field=models.IntegerField(blank=True, null=True, verbose_name='Дни повторного заказа поставки'),
        ),
    ]
