# Generated by Django 3.2.7 on 2021-10-21 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_auto_20211006_1440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='linck_to_ozon',
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.CharField(max_length=50, verbose_name='Cумма заказа'),
        ),
        migrations.AlterField(
            model_name='product',
            name='reorder_days_of_supply',
            field=models.IntegerField(blank=True, null=True, verbose_name='Глубина поставки'),
        ),
    ]
