# Generated by Django 3.2.7 on 2021-10-21 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_auto_20211021_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(max_length=500, verbose_name='Номер заказа'),
        ),
    ]
