# Generated by Django 3.2.7 on 2021-10-26 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_product_marketing_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='marketing_price',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Цена'),
        ),
    ]
