# Generated by Django 3.2.7 on 2021-10-28 13:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0020_alter_product_marketing_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='comission',
        ),
        migrations.RemoveField(
            model_name='order',
            name='name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='number',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_place',
        ),
        migrations.RemoveField(
            model_name='order',
            name='price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='profit',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_warehouse',
        ),
        migrations.RemoveField(
            model_name='order',
            name='sku',
        ),
        migrations.RemoveField(
            model_name='product',
            name='average_order_speed',
        ),
        migrations.RemoveField(
            model_name='product',
            name='average_unit_profit',
        ),
        migrations.RemoveField(
            model_name='product',
            name='deliveries',
        ),
        migrations.RemoveField(
            model_name='product',
            name='history',
        ),
        migrations.RemoveField(
            model_name='product',
            name='need_to_order',
        ),
        migrations.RemoveField(
            model_name='product',
            name='potential_profit',
        ),
        migrations.RemoveField(
            model_name='product',
            name='reorder_profit',
        ),
        migrations.RemoveField(
            model_name='product',
            name='reorder_summ',
        ),
        migrations.RemoveField(
            model_name='product',
            name='reordering_date',
        ),
        migrations.RemoveField(
            model_name='product',
            name='return_product',
        ),
        migrations.RemoveField(
            model_name='product',
            name='status',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock_for_days',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock_profit',
        ),
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='order',
            name='creating_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Тип доставки'),
        ),
        migrations.AddField(
            model_name='order',
            name='in_process_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата принятия в обработку'),
        ),
        migrations.AddField(
            model_name='order',
            name='posting_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Номер отправления'),
        ),
        migrations.AddField(
            model_name='order',
            name='region',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Регион'),
        ),
        migrations.AddField(
            model_name='order',
            name='warehous_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID склада'),
        ),
        migrations.AddField(
            model_name='order',
            name='warehouse_name',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Склад отгрузки'),
        ),
        migrations.AddField(
            model_name='product',
            name='creating_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='additional_price',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Дополнительные затраты'),
        ),
        migrations.AlterField(
            model_name='product',
            name='logistics_price',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Цена логистики'),
        ),
        migrations.AlterField(
            model_name='product',
            name='summ_price',
            field=models.FloatField(blank=True, null=True, verbose_name='Итого'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_price',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Цена юнита'),
        ),
        migrations.CreateModel(
            name='ProductInOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=100, verbose_name='SKU')),
                ('name', models.CharField(max_length=300, verbose_name='Название товара')),
                ('quantity', models.IntegerField(verbose_name='Кол-во')),
                ('offer_id', models.CharField(max_length=15, verbose_name='Номер предложения')),
                ('price', models.FloatField(verbose_name='Цена товара')),
                ('comission_amount', models.FloatField(verbose_name='Сумма комиссий')),
                ('payout', models.FloatField(verbose_name='Cтоимость товара')),
                ('product_id', models.IntegerField(verbose_name='ID продукта')),
                ('fulfillment', models.FloatField(verbose_name='Выполнение предмета услуг на торговой площадке')),
                ('direct_flow_trans', models.FloatField(verbose_name='Транзит товара на маркетплейсе')),
                ('return_flow_trans', models.FloatField(verbose_name='Возврат товара через')),
                ('deliv_to_customer', models.FloatField(verbose_name='Доставка товара покупателю')),
                ('return_not_deliv_to_customer', models.FloatField(verbose_name='Возврат товара от покупателя')),
                ('return_part_goods_customer', models.FloatField(verbose_name='Возврат части заказа покупателю')),
                ('return_after_deliv_to_customer', models.FloatField(verbose_name='Возврат доставленного товара')),
                ('creating_date', models.DateField(auto_now_add=True)),
                ('order_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orderproduct_to_order', to='product.order')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orderproduct_to_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'заказаный товар',
                'verbose_name_plural': 'заказаные товары',
                'ordering': ['id'],
            },
        ),
    ]
