# Generated by Django 3.2.7 on 2021-10-28 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_auto_20211028_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='reserved',
            field=models.IntegerField(blank=True, null=True, verbose_name='Зарезервировано'),
        ),
    ]
