# Generated by Django 3.2.7 on 2021-11-18 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0028_ozonmetrics'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinorder',
            name='preview',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Превью'),
        ),
    ]
