# Generated by Django 3.2.7 on 2021-11-18 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0029_productinorder_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='posting_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Номер отправления'),
        ),
        migrations.AlterField(
            model_name='productinorder',
            name='offer_id',
            field=models.CharField(max_length=100, verbose_name='Номер предложения'),
        ),
    ]
