# Generated by Django 3.2.11 on 2022-01-13 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
        ('product', '0033_auto_20211208_1203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ozonmetrics',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='ozontransactions',
            name='product',
        ),
        migrations.RemoveField(
            model_name='ozontransactions',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='productinorder',
            name='order_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orderproduct_to_order', to='order.order'),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OzonMetrics',
        ),
        migrations.DeleteModel(
            name='OzonTransactions',
        ),
    ]
