# Generated by Django 3.2.11 on 2022-01-21 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0034_auto_20220113_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='summ_price',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Итого'),
        ),
    ]
