# Generated by Django 3.2.11 on 2022-01-21 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0035_alter_product_summ_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='summ_price',
            field=models.FloatField(default=0, verbose_name='Итого'),
        ),
    ]
