# Generated by Django 3.2.11 on 2022-01-25 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0040_product_marketplace_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_visible',
            field=models.BooleanField(default=True, verbose_name='Видимость товара'),
        ),
    ]
