# Generated by Django 3.2.11 on 2022-01-26 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0043_auto_20220126_0947'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'ordering': ['id'], 'verbose_name': 'Категорию', 'verbose_name_plural': 'Категории'},
        ),
    ]
