# Generated by Django 3.2.11 on 2022-01-26 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0035_alter_productinorder_summ_price'),
        ('product', '0044_alter_categories_options'),
    ]

    operations = [
    ]
