# Generated by Django 3.2.11 on 2022-01-26 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0045_merge_20220126_1232'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'ordering': ['name'], 'verbose_name': 'Категорию', 'verbose_name_plural': 'Категории'},
        ),
    ]
