# Generated by Django 3.2.7 on 2021-09-17 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20210908_1257'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['id'], 'verbose_name': 'Товар', 'verbose_name_plural': 'товары'},
        ),
        migrations.AlterModelOptions(
            name='warehouseaccounting',
            options={'ordering': ['id'], 'verbose_name': 'Складской учет', 'verbose_name_plural': 'складской учёт'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='hours_for_production',
        ),
        migrations.RemoveField(
            model_name='product',
            name='leftovers',
        ),
        migrations.RemoveField(
            model_name='product',
            name='minutes_for_production',
        ),
        migrations.AlterField(
            model_name='product',
            name='additional_price',
            field=models.IntegerField(default=0, verbose_name='Дополнительные затраты'),
        ),
        migrations.AlterField(
            model_name='product',
            name='days_for_production',
            field=models.IntegerField(blank=True, null=True, verbose_name='Времени необходимо для производства'),
        ),
        migrations.AlterField(
            model_name='product',
            name='logistics_price',
            field=models.IntegerField(default=0, verbose_name='Цена логистики'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=300, verbose_name='Название товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='preview',
            field=models.ImageField(blank=True, upload_to='preview/%y/%m/%d/', verbose_name='Превью'),
        ),
        migrations.AlterField(
            model_name='product',
            name='reorder_days_of_supply',
            field=models.IntegerField(verbose_name='Дней для повторного заказа'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(max_length=100, verbose_name='SKU'),
        ),
        migrations.AlterField(
            model_name='product',
            name='summ_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Итого'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_price',
            field=models.IntegerField(default=0, verbose_name='Цена юнита'),
        ),
        migrations.AlterField(
            model_name='warehouseaccounting',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_and_warehouse', to='product.product', verbose_name='Название продукта'),
        ),
    ]
