# Generated by Django 3.2.7 on 2021-09-21 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20210917_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='additional_price',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Дополнительные затраты'),
        ),
        migrations.AlterField(
            model_name='product',
            name='logistics_price',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Цена логистики'),
        ),
        migrations.AlterField(
            model_name='product',
            name='reorder_days_of_supply',
            field=models.IntegerField(blank=True, null=True, verbose_name='Дней для повторного заказа'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_price',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Цена юнита'),
        ),
    ]
