# Generated by Django 3.2.7 on 2021-09-21 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20210921_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ozon_product_id',
            field=models.CharField(default='0', max_length=100, verbose_name='ID товара'),
        ),
    ]
