# Generated by Django 3.2.7 on 2021-09-21 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_product_ozon_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ozon_product_id',
            field=models.IntegerField(verbose_name='ID товара'),
        ),
    ]
