# Generated by Django 3.2.7 on 2021-09-22 09:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0009_auto_20210922_0731'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products_to_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
