# Generated by Django 3.2.7 on 2021-10-26 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_alter_order_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='marketing_price',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Цена'),
        ),
    ]
