# Generated by Django 3.2.7 on 2021-11-01 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_product_reserved'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinorder',
            name='price_f',
            field=models.FloatField(blank=True, null=True, verbose_name='Цена товара в заказе'),
        ),
        migrations.AlterField(
            model_name='order',
            name='warehous_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='ID склада'),
        ),
    ]
