# Generated by Django 3.2.7 on 2021-11-03 09:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0023_auto_20211101_0822'),
    ]

    operations = [
        migrations.CreateModel(
            name='OzonTransactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_id', models.IntegerField(verbose_name='Номер опирации')),
                ('operation_type', models.CharField(max_length=250, verbose_name='Тип опирации')),
                ('operation_date', models.DateTimeField(verbose_name='Дата опирации')),
                ('operation_type_name', models.CharField(max_length=250, verbose_name='Название типа опирации')),
                ('accruals_for_sale', models.IntegerField(verbose_name='Начисления за продажу')),
                ('sale_commission', models.IntegerField(verbose_name='Комиссия за продажу')),
                ('amount', models.IntegerField(verbose_name='Amount')),
                ('type', models.CharField(max_length=250, verbose_name='Тип')),
                ('posting_number', models.CharField(max_length=15, verbose_name='Номер доставки')),
                ('items', models.CharField(max_length=5000, verbose_name='Товары')),
                ('services', models.CharField(max_length=10000, verbose_name='Виды услуг')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ozon_transaction_to_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'транзакцию ozon',
                'verbose_name_plural': 'транзакции ozon',
                'ordering': ['id'],
            },
        ),
    ]
