# Generated by Django 3.2.7 on 2021-11-03 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0024_ozontransactions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ozontransactions',
            name='accruals_for_sale',
            field=models.FloatField(verbose_name='Начисления за продажу'),
        ),
        migrations.AlterField(
            model_name='ozontransactions',
            name='amount',
            field=models.FloatField(verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='ozontransactions',
            name='sale_commission',
            field=models.FloatField(verbose_name='Комиссия за продажу'),
        ),
    ]
