# Generated by Django 3.2.7 on 2021-11-11 11:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0027_alter_ozontransactions_posting_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='OzonMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField(verbose_name='ID товара')),
                ('product_name', models.CharField(max_length=300, verbose_name='Название товара')),
                ('hits_view_search', models.FloatField(verbose_name='показы в поиске и в категории')),
                ('hits_view_pdp', models.FloatField(verbose_name='показы на карточке товара')),
                ('hits_view', models.FloatField(verbose_name='всего показов')),
                ('hits_tocart_search', models.FloatField(verbose_name='в корзину из поиска или категории')),
                ('hits_tocart_pdp', models.FloatField(verbose_name='в корзину из карточки товара')),
                ('hits_tocart', models.FloatField(verbose_name='всего добавлено в корзину')),
                ('session_view_search', models.FloatField(verbose_name='сессии с показом в поиске или в категории')),
                ('session_view_pdp', models.FloatField(verbose_name='сессии с показом на карточке товара')),
                ('session_view', models.FloatField(verbose_name='всего сессий')),
                ('conv_tocart_search', models.FloatField(verbose_name='конверсия в корзину из поиска или категории')),
                ('conv_tocart_pdp', models.FloatField(verbose_name='конверсия в корзину из карточки товара')),
                ('conv_tocart', models.FloatField(verbose_name='общая конверсия в корзину')),
                ('revenue', models.FloatField(verbose_name='заказано на сумму')),
                ('returns', models.FloatField(verbose_name='возвращено товаров')),
                ('cancellations', models.FloatField(verbose_name='отменено товаров')),
                ('ordered_units', models.FloatField(verbose_name='заказано товаров')),
                ('delivered_units', models.FloatField(verbose_name='доставлено товаров')),
                ('adv_view_pdp', models.FloatField(verbose_name='показы на карточке товара, спонсорские товары')),
                ('adv_view_search_category', models.FloatField(verbose_name='показы в поиске и в категории, спонсорские товары')),
                ('adv_view_all', models.FloatField(verbose_name='показы всего, спонсорские товары,')),
                ('adv_sum_all', models.FloatField(verbose_name='всего расходов на рекламу')),
                ('position_category', models.FloatField(verbose_name='позиция в поиске и категории')),
                ('postings', models.FloatField(verbose_name='отправления')),
                ('postings_premium', models.FloatField(verbose_name='отправления с подпиской Premium')),
                ('creating_date', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ozon_metrics_to_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Метрика',
                'verbose_name_plural': 'метрики',
                'ordering': ['id'],
            },
        ),
    ]
