# Generated by Django 3.2.7 on 2021-12-01 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0030_auto_20211118_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='ozontransactions',
            name='product',
            field=models.ManyToManyField(blank=True, null=True, related_name='product_in_transaction', to='product.ProductInOrder'),
        ),
    ]
