# Generated by Django 3.2.7 on 2021-12-08 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0032_remove_ozontransactions_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinorder',
            name='additional_price',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Дополнительные затраты'),
        ),
        migrations.AddField(
            model_name='productinorder',
            name='days_for_production',
            field=models.IntegerField(blank=True, null=True, verbose_name='Времени необходимо для производства'),
        ),
        migrations.AddField(
            model_name='productinorder',
            name='logistics_price',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Цена логистики'),
        ),
        migrations.AddField(
            model_name='productinorder',
            name='reorder_days_of_supply',
            field=models.IntegerField(blank=True, null=True, verbose_name='Глубина поставки'),
        ),
        migrations.AddField(
            model_name='productinorder',
            name='summ_price',
            field=models.FloatField(blank=True, null=True, verbose_name='Итого'),
        ),
        migrations.AddField(
            model_name='productinorder',
            name='unit_price',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Цена юнита'),
        ),
    ]
