# Generated by Django 3.2.11 on 2022-01-13 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marketplace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marketplace_name', models.CharField(max_length=100, verbose_name='Название маркетплейса')),
                ('marketplace_id', models.IntegerField(blank=True, default=0, null=True, verbose_name='ID пользователя маркетплейса')),
                ('api_key', models.CharField(blank=True, max_length=500, null=True, verbose_name='API ключ')),
                ('last_validations_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата последней проверки')),
            ],
            options={
                'verbose_name': 'маркетплейс',
                'verbose_name_plural': 'маркетплейсы',
                'ordering': ('id',),
            },
        ),
    ]
