# Generated by Django 3.2.11 on 2022-01-14 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplace',
            name='marketplace_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Тип маркетплейса'),
        ),
    ]
