# Generated by Django 3.2.11 on 2022-01-14 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_auto_20220114_0749'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplace',
            name='valid',
            field=models.BooleanField(default=False, verbose_name='Активный'),
        ),
    ]
