# Generated by Django 3.2.11 on 2022-01-17 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_marketplace_valid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketplace',
            name='marketplace_type',
            field=models.CharField(default='ozon', max_length=100, verbose_name='Тип маркетплейса'),
        ),
    ]
