# Generated by Django 3.2.11 on 2022-01-13 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_name', models.CharField(default='base', max_length=200, verbose_name='Название тарифа')),
                ('validity', models.IntegerField(verbose_name='Срок действия в днях')),
                ('price', models.FloatField(verbose_name='Стоимость тарифа')),
                ('description', models.CharField(max_length=1500, verbose_name='Краткое описание тарифа')),
                ('slag', models.CharField(max_length=100, verbose_name='роль, которую дает тариф')),
            ],
            options={
                'verbose_name': 'тариф',
                'verbose_name_plural': 'тарифы',
                'ordering': ['id'],
            },
        ),
    ]
