# Generated by Django 3.2.11 on 2022-01-13 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_number', models.CharField(default='000000000000000', max_length=200, verbose_name='Номер транзакции')),
                ('date_issued', models.DateTimeField(auto_now_add=True, verbose_name='Дата выполнения')),
                ('summ', models.IntegerField(default=0, verbose_name='Сумма списания')),
                ('status', models.CharField(blank=True, default='wait', max_length=100, verbose_name='Статус')),
                ('id_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_transaction', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('rate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rate_transaction', to='rate.rate', verbose_name='Тариф')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_transaction', to='payment.paymenttype', verbose_name='Способ оплаты')),
            ],
            options={
                'verbose_name': 'транзакцию',
                'verbose_name_plural': 'транзакции',
                'ordering': ['id'],
            },
        ),
    ]
