# Generated by Django 3.2.7 on 2022-01-21 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='amount',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Прибыль'),
        ),
        migrations.AddField(
            model_name='order',
            name='summ_comission',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Сумма комиссий'),
        ),
    ]
