# Generated by Django 3.2.11 on 2022-01-26 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='amount',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Прибыль'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_visible',
            field=models.BooleanField(default=True, verbose_name='Видимость товара'),
        ),
        migrations.AddField(
            model_name='order',
            name='marketplace_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID маркетплейса'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_sum',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Сумма заказа'),
        ),
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Количество'),
        ),
        migrations.AddField(
            model_name='order',
            name='summ_comission',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Сумма комиссий'),
        ),
    ]
