# Generated by Django 3.2.11 on 2022-01-25 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_order_is_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='amount',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Прибыль'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_sum',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Сумма заказа'),
        ),
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Количество'),
        ),
        migrations.AddField(
            model_name='order',
            name='summ_comission',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Сумма комиссий'),
        ),
    ]
