# Generated by Django 3.2.11 on 2022-01-13 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0034_auto_20220113_1452'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OzonTransactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_id', models.BigIntegerField(verbose_name='Номер опирации')),
                ('operation_type', models.CharField(max_length=250, verbose_name='Тип опирации')),
                ('operation_date', models.DateTimeField(verbose_name='Дата опирации')),
                ('operation_type_name', models.CharField(max_length=250, verbose_name='Название типа опирации')),
                ('accruals_for_sale', models.FloatField(verbose_name='Начисления за продажу')),
                ('sale_commission', models.FloatField(verbose_name='Комиссия за продажу')),
                ('amount', models.FloatField(verbose_name='Amount')),
                ('type', models.CharField(max_length=250, verbose_name='Тип')),
                ('posting_number', models.CharField(max_length=500, verbose_name='Номер доставки')),
                ('services', models.CharField(max_length=10000, verbose_name='Виды услуг')),
                ('product', models.ManyToManyField(blank=True, null=True, related_name='product_in_transaction', to='product.ProductInOrder')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ozon_transaction_to_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'транзакцию ozon',
                'verbose_name_plural': 'транзакции ozon',
                'ordering': ['id'],
            },
        ),
    ]
