# Generated by Django 3.2.7 on 2021-09-05 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['id'], 'verbose_name': 'Транзакция', 'verbose_name_plural': 'Транзакции'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['id'], 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterModelOptions(
            name='userpayment',
            options={'ordering': ['id'], 'verbose_name': 'Данные оплаты', 'verbose_name_plural': 'Данные оплаты'},
        ),
        migrations.AddField(
            model_name='transaction',
            name='date_issued',
            field=models.DateTimeField(default='2000-01-01'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment_type',
            field=models.CharField(default='card payment', max_length=100),
        ),
        migrations.AddField(
            model_name='transaction',
            name='rate',
            field=models.CharField(default='base', max_length=100),
        ),
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(default='wait', max_length=100),
        ),
        migrations.AddField(
            model_name='transaction',
            name='summ',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_number',
            field=models.CharField(default='000000000000000', max_length=200),
        ),
    ]
