# Generated by Django 3.2.7 on 2021-09-07 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_data', '0003_auto_20210907_0700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpayment',
            name='entity_data',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
    ]
