# Generated by Django 3.2.7 on 2021-09-17 13:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('get_data', '0007_alter_userpayment_id_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['id'], 'verbose_name': 'транзакция', 'verbose_name_plural': 'транзакции'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('id',), 'verbose_name': 'пользователь', 'verbose_name_plural': 'пользователи'},
        ),
        migrations.AlterModelOptions(
            name='userpayment',
            options={'ordering': ['id'], 'verbose_name': 'данные оплаты', 'verbose_name_plural': 'данные оплаты'},
        ),
        migrations.RemoveField(
            model_name='userpayment',
            name='entity_data',
        ),
        migrations.AddField(
            model_name='userpayment',
            name='bank',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Название банка'),
        ),
        migrations.AddField(
            model_name='userpayment',
            name='bank_account',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер счёта'),
        ),
        migrations.AddField(
            model_name='userpayment',
            name='bik',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='БИК'),
        ),
        migrations.AddField(
            model_name='userpayment',
            name='correspondent_bank_account',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Кореспондентский счёт'),
        ),
        migrations.AddField(
            model_name='userpayment',
            name='inn',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='ИНН'),
        ),
        migrations.AddField(
            model_name='userpayment',
            name='kpp',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='КПП'),
        ),
        migrations.AddField(
            model_name='userpayment',
            name='name_org',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Название организации'),
        ),
        migrations.AddField(
            model_name='userpayment',
            name='orgn',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='ОРГН'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date_issued',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата выполнения'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='id_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_transaction', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payment_type',
            field=models.CharField(default='card payment', max_length=100, verbose_name='Способ оплаты'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='rate',
            field=models.CharField(default='base', max_length=100, verbose_name='Тариф'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(default='wait', max_length=100, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='summ',
            field=models.IntegerField(default=0, verbose_name='Сумма списания'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_number',
            field=models.CharField(default='000000000000000', max_length=200, verbose_name='Номер транзакции'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Активный пользователь'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='Персонал'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False, verbose_name='Администратор'),
        ),
        migrations.AlterField(
            model_name='userpayment',
            name='card',
            field=models.CharField(max_length=16, verbose_name='Карта'),
        ),
        migrations.AlterField(
            model_name='userpayment',
            name='id_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_payment', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
