# Generated by Django 3.2.7 on 2021-09-20 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_data', '0008_auto_20210917_1323'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['id'], 'verbose_name': 'транзакцию', 'verbose_name_plural': 'транзакции'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('id',), 'verbose_name': 'пользователя', 'verbose_name_plural': 'пользователи'},
        ),
        migrations.AddField(
            model_name='user',
            name='bank',
            field=models.CharField(blank=True, default='bank', max_length=1000, null=True, verbose_name='Название банка'),
        ),
        migrations.AddField(
            model_name='user',
            name='bank_account',
            field=models.CharField(blank=True, default='00000000000000000000', max_length=20, null=True, verbose_name='Номер счёта'),
        ),
        migrations.AddField(
            model_name='user',
            name='bik',
            field=models.CharField(blank=True, default='00000000', max_length=8, null=True, verbose_name='БИК'),
        ),
        migrations.AddField(
            model_name='user',
            name='card',
            field=models.CharField(default='0000000000000000', max_length=16, verbose_name='Карта'),
        ),
        migrations.AddField(
            model_name='user',
            name='correspondent_bank_account',
            field=models.CharField(blank=True, default='00000000000000000000', max_length=20, null=True, verbose_name='Кореспондентский счёт'),
        ),
        migrations.AddField(
            model_name='user',
            name='inn',
            field=models.CharField(blank=True, default='000000000000', max_length=12, null=True, verbose_name='ИНН'),
        ),
        migrations.AddField(
            model_name='user',
            name='kpp',
            field=models.CharField(blank=True, default='000000000', max_length=9, null=True, verbose_name='КПП'),
        ),
        migrations.AddField(
            model_name='user',
            name='name_org',
            field=models.CharField(blank=True, default='organization', max_length=256, null=True, verbose_name='Название организации'),
        ),
        migrations.AddField(
            model_name='user',
            name='orgn',
            field=models.CharField(blank=True, default='000000000000', max_length=12, null=True, verbose_name='ОРГН'),
        ),
        migrations.DeleteModel(
            name='UserPayment',
        ),
    ]
