# Generated by Django 3.2.7 on 2021-09-22 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('get_data', '0011_auto_20210922_0913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='products',
        ),
    ]
