# Generated by Django 3.2.7 on 2021-09-23 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_data', '0012_remove_user_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bank',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Название банка'),
        ),
        migrations.AlterField(
            model_name='user',
            name='bank_account',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер счёта'),
        ),
        migrations.AlterField(
            model_name='user',
            name='bik',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='БИК'),
        ),
        migrations.AlterField(
            model_name='user',
            name='card',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Карта'),
        ),
        migrations.AlterField(
            model_name='user',
            name='correspondent_bank_account',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Кореспондентский счёт'),
        ),
        migrations.AlterField(
            model_name='user',
            name='inn',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='user',
            name='kpp',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='КПП'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name_org',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Название организации'),
        ),
        migrations.AlterField(
            model_name='user',
            name='orgn',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='ОРГН'),
        ),
    ]
