# Generated by Django 3.2.7 on 2021-10-04 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('get_data', '0013_auto_20210923_0817'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='card', max_length=100, verbose_name='Способ оплаты')),
                ('description', models.CharField(max_length=1000, verbose_name='Описание способа оплаты')),
            ],
            options={
                'verbose_name': 'способ оплаты',
                'verbose_name_plural': 'способы оплаты',
                'ordering': ['type'],
            },
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payment_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_transaction', to='get_data.paymenttype', verbose_name='Способ оплаты'),
        ),
    ]
