# Generated by Django 3.2.7 on 2021-10-05 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('get_data', '0016_auto_20211004_2105'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='card_yer',
            new_name='card_year',
        ),
    ]
