# Generated by Django 3.2.7 on 2021-10-05 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_data', '0017_rename_card_yer_user_card_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='api_key',
            field=models.CharField(blank=True, default='Null', max_length=500, null=True, verbose_name='API ключ OZON'),
        ),
        migrations.AlterField(
            model_name='user',
            name='ozon_id',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='ID пользователя OZON'),
        ),
    ]
