# Generated by Django 3.2.7 on 2021-10-06 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_data', '0019_auto_20211005_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='api_key',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='API ключ OZON'),
        ),
        migrations.AlterField(
            model_name='user',
            name='card_ovner',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Данные владельца карты'),
        ),
        migrations.AlterField(
            model_name='user',
            name='card_year',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Срок действия карты'),
        ),
    ]
