# Generated by Django 3.2.7 on 2021-11-04 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_data', '0021_auto_20211104_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(blank=True, default='wait', max_length=100, verbose_name='Статус'),
        ),
    ]
