# Generated by Django 3.2.7 on 2021-11-11 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_data', '0022_alter_transaction_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='rate_name',
            field=models.CharField(default='base', max_length=200, verbose_name='Название тарифа'),
        ),
    ]
