# Generated by Django 3.2.7 on 2021-11-22 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_data', '0023_alter_rate_rate_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='slag',
            field=models.CharField(blank=True, default='subscription', max_length=100, null=True, verbose_name='роль, которую дает тариф'),
        ),
    ]
