# Generated by Django 3.2.7 on 2021-11-23 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_data', '0024_rate_slag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='slag',
            field=models.CharField(max_length=100, verbose_name='роль, которую дает тариф'),
        ),
    ]
