# Generated by Django 3.2.7 on 2021-12-23 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_data', '0025_alter_rate_slag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marketplace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marketplace_name', models.CharField(max_length=100, verbose_name='Название маркетплейса')),
                ('marketplace_id', models.IntegerField(blank=True, default=0, null=True, verbose_name='ID пользователя маркетплейса')),
                ('api_key', models.CharField(blank=True, max_length=500, null=True, verbose_name='API ключ')),
                ('last_validations_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата последней проверки')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='marketplace_data',
            field=models.ManyToManyField(blank=True, null=True, related_name='user_marketplace', to='get_data.Marketplace'),
        ),
    ]
