# Generated by Django 3.2.11 on 2022-01-10 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('get_data', '0026_auto_20211223_1017'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marketplace',
            options={'ordering': ('id',), 'verbose_name': 'маркетплейс', 'verbose_name_plural': 'маркетплейсы'},
        ),
    ]
