# Generated by Django 3.2.7 on 2022-01-09 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_data', '0026_auto_20211223_1017'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marketplace',
            options={'ordering': ('id',), 'verbose_name': 'маркетплейс', 'verbose_name_plural': 'маркетплейсы'},
        ),
        migrations.AlterField(
            model_name='marketplace',
            name='api_key',
            field=models.CharField(blank=True, max_length=500, null=True, unique=True, verbose_name='API ключ'),
        ),
        migrations.AlterField(
            model_name='marketplace',
            name='marketplace_id',
            field=models.IntegerField(blank=True, default=0, null=True, unique=True, verbose_name='ID пользователя маркетплейса'),
        ),
    ]
