# Generated by Django 3.2.7 on 2022-01-11 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_data', '0027_auto_20220109_2004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='api_key',
        ),
        migrations.RemoveField(
            model_name='user',
            name='ozon_id',
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='photos/%y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='marketplace',
            name='marketplace_name',
            field=models.CharField(choices=[('ozon', 'ozon')], max_length=100, verbose_name='Название маркетплейса'),
        ),
    ]
